etcd:
    image: quay.io/coreos/etcd:v0.4.6
    container_name: etcd
    
    # need to advertise the correct address for confd
    command: -addr=etcd:4001

mongo:
    image: mongo:3.0
    container_name: mongo

haproxy:
    build: haproxy
    container_name: haproxy
    ports:
        - "80:80"
        - "81:81"

graylog:
    image: graylog2/allinone:latest
    container_name: graylog
    ports:
        - "9000:9000"
        - "12201:12201"
        - "12202:12202/udp"
        - "12209:12209"

sling_001:
    build: sling
    ports:
        - "8080:8080"
    environment:
       - SLING_DB=sling_001
       - SLING_PORT=8080
       - SLING_DOMAIN=alpha.example.com

sling_002:
    build: sling
    ports:
        - "8081:8081"
    environment:
       - SLING_DB=sling_002
       - SLING_PORT=8081
       - SLING_DOMAIN=bravo.example.com

sling_003:
    build: sling
    ports:
        - "8082:8082"
    environment:
       - SLING_DB=sling_003
       - SLING_PORT=8082
       - SLING_DOMAIN=charlie.example.com

sling_004:
    build: sling
    ports:
        - "8083:8083"
    environment:
       - SLING_DB=sling_004
       - SLING_PORT=8083
       - SLING_DOMAIN=delta.example.com


