etcd:
    image: quay.io/coreos/etcd:v0.4.6

mongo:
    image: mongo:3.0

haproxy:
    build: haproxy
    ports:
        - "80:80"
    links:
        - etcd

sling_001:
    build: sling
    ports:
        - "8080:8080"
    links:
        - mongo
        - etcd
    environment:
       - SLING_DB=sling_001
       - SLING_PORT=8080